export enum Role {
  ADMIN = 'ADMIN',
  ADMIN_COUNTRY = 'ADMIN_COUNTRY',
  USER = 'USER',
  COORDINADOR = 'COORDINADOR',
  SUPERVISOR = 'SUPERVISOR',
  PSICOLOGO = 'PSICOLOGO',
  ORIENTADOR = 'ORIENTADOR',
  TRABAJO_SOCIAL = 'TRABAJO_SOCIAL',
}
